apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: namespace-team-3
    crossplane.io/external-create-pending: "2024-01-23T02:37:06Z"
    crossplane.io/external-create-succeeded: "2024-01-23T02:37:06Z"
    crossplane.io/external-name: dev-teams-kwvvm
  creationTimestamp: "2024-01-23T02:37:06Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: dev-teams-
  generation: 1
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: dev-teams
  name: dev-teams-kwvvm
  ownerReferences:
  - apiVersion: k8s.example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XTenant
    name: dev-teams
    uid: 2b162599-5852-4e27-9df9-c130ea07945d
  resourceVersion: "154059"
  uid: f32d4da1-95e3-4abc-8ada-4541f97d0953
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: team-3
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
  readiness:
    policy: SuccessfulCreate
status:
  atProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"team-3"}}'
        creationTimestamp: "2024-01-23T02:37:06Z"
        labels:
          kubernetes.io/metadata.name: team-3
        managedFields:
        - apiVersion: v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
              f:labels:
                .: {}
                f:kubernetes.io/metadata.name: {}
          manager: crossplane-kubernetes-provider
          operation: Update
          time: "2024-01-23T02:37:06Z"
        name: team-3
        resourceVersion: "154045"
        uid: 11672934-1e6b-4378-b506-7eda585bdb6e
      spec:
        finalizers:
        - kubernetes
      status:
        phase: Active
  conditions:
  - lastTransitionTime: "2024-01-23T02:37:06Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-01-23T02:37:06Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
